sudo: required
services:
- docker
language: bash
script:
- |
  curl https://get.docker.com | sh
  mkdir -p ~/.docker
  echo '{ "experimental": "enabled" }' > ~/.docker/config.json
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker run aarch64/ubuntu /bin/bash --version
