sudo: required

language: bash

services:
  - docker

script:
  - sudo apt-get update
  - sudo apt-get install qemu-user-static
  - docker run --rm -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static aarch64/ubuntu /bin/bash --version

