sudo: required
services:
- docker
language: bash
script:
- |
  curl https://get.docker.com | sh
  mkdir -p ~/.docker
  echo '{ "experimental": "enabled" }' > ~/.docker/config.json
  docker version
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- ls -al /usr/bin/qemu-aarch64-static
- docker run --rm -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static aarch64/ubuntu /bin/bash --version
